name: Build
env:
  CI: true
on:
  push:
    branches:
      - master
      - develop
  pull_request:
jobs:
  ANDROID_BASE_CHECKS:
    name: Base Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Perform base checks
        run: ./gradlew app:assembleDebug
  KTLINT_CHECK:
    name: ktlint quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Perform ktlint
        run: ./gradlew app:ktlint
  ANDROID_UNIT_TESTS:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Execute unit tests
        run: ./gradlew app:jacocoTestReport
      - name: Upload unit tests artifact
        uses: actions/upload-artifact@v1
        with:
          name: unit_tests
          path: ./app/build/jacoco/
      - name: Upload coverage report (Codecov)
        uses: codecov/codecov-action@v1
        with:
          name: unit_tests
          file: ./app/build/jacoco/jacoco.xml
          fail_ci_if_error: true
  ANDROID_EMULATOR_TESTS:
    name: Emulator Tests
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        EMULATOR_API: [26, 27, 28, 29]
        include:
          - EMULATOR_API: 29
            EMULATOR_ARCH: x86_64
          - EMULATOR_API: 28
            EMULATOR_ARCH: x86_64
          - EMULATOR_API: 27
            EMULATOR_ARCH: x86_64
          - EMULATOR_API: 26
            EMULATOR_ARCH: x86_64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Execute emulator tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2.2.0
        with:
          api-level: ${{ matrix.EMULATOR_API }}
          arch: ${{ matrix.EMULATOR_ARCH }}
          disable-animations: true
          profile: Nexus 5X
          emulator-options: -no-snapshot -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect
          emulator-build: 6110076
          script: ./gradlew app:connectedCheck
      - name: Upload emulator tests artifact
        uses: actions/upload-artifact@v1
        with:
          name: emulator_tests_${{ matrix.EMULATOR_API }}
          path: ./app/build/reports/coverage/debug/
      - name: Upload coverage report (Codecov)
        uses: codecov/codecov-action@v1
        with:
          name: emulator_tests_${{ matrix.EMULATOR_API }}
          file: ./app/build/reports/coverage/debug/report.xml
          fail_ci_if_error: true